---
- hosts: 47.92.85.59
  vars:
    repo_folder: /workspace
  remote_user: root
  tasks:

    - name: "Create directory if not exists"
      file:
        path: "{{ repo_folder }}"
        state: directory
        mode: 0755
        group: root
        owner: root

    - name: kill old process
      shell: sudo kill -9 $(lsof -i:8000 -t)
      ignore_errors: true

    - name: clone repository
      git:
        repo: https://github.com/UncoDong/back-end.git
        dest: "{{ repo_folder }}"
        update: yes
        force: yes

    - name: start server
      shell: "cd {{ repo_folder }} && nohup sudo python {{ repo_folder }}/MusicBackEnd/manage.py runserver > {{ repo_folder }}/MusicBackEnd/Music.log 2>&1 &"